name: netflims
services:
- name: netflims-web
  github:
    repo: dhirajgupta9870/netflim
    branch: main
  source_dir: /
  build_command: npm install 2>/dev/null || echo "No npm needed"
  run_command: echo "Serving static files"
  http_port: 8080
  envs:
  - key: NODE_ENV
    value: production
